version: '3.3'
services:
  cloudflared-tunnel:
    image: cloudflare/cloudflared:2022.7.1
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    restart: always
    network_mode: host
  vless:
    image: rossbutler/vless@sha256:07fd750b0e7e560355b210fa3938cbafec3ca6cb3638261a39c23909fb82f01d
    network_mode: host
